// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(themiracle_trackingFFI)
import themiracle_trackingFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_themiracle_tracking_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_themiracle_tracking_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureThemiracleTrackingInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol TrackerProtocol: AnyObject, Sendable {
    
    func flush() throws 
    
    func setConsent(enabled: Bool) 
    
    func setSession(sessionId: String?) 
    
    func setUser(userId: String?) 
    
    func track(event: TrackEvent) throws 
    
}
open class Tracker: TrackerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_themiracle_tracking_fn_clone_tracker(self.handle, $0) }
    }
public convenience init(config: SdkConfig) {
    let handle =
        try! rustCall() {
    uniffi_themiracle_tracking_fn_constructor_tracker_new(
        FfiConverterTypeSdkConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_themiracle_tracking_fn_free_tracker(handle, $0) }
    }

    

    
open func flush()throws   {try rustCallWithError(FfiConverterTypeSdkError_lift) {
    uniffi_themiracle_tracking_fn_method_tracker_flush(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func setConsent(enabled: Bool)  {try! rustCall() {
    uniffi_themiracle_tracking_fn_method_tracker_set_consent(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(enabled),$0
    )
}
}
    
open func setSession(sessionId: String?)  {try! rustCall() {
    uniffi_themiracle_tracking_fn_method_tracker_set_session(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(sessionId),$0
    )
}
}
    
open func setUser(userId: String?)  {try! rustCall() {
    uniffi_themiracle_tracking_fn_method_tracker_set_user(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(userId),$0
    )
}
}
    
open func track(event: TrackEvent)throws   {try rustCallWithError(FfiConverterTypeSdkError_lift) {
    uniffi_themiracle_tracking_fn_method_tracker_track(
            self.uniffiCloneHandle(),
        FfiConverterTypeTrackEvent_lower(event),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTracker: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Tracker

    public static func lift(_ handle: UInt64) throws -> Tracker {
        return Tracker(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Tracker) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Tracker {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Tracker, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTracker_lift(_ handle: UInt64) throws -> Tracker {
    return try FfiConverterTypeTracker.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTracker_lower(_ value: Tracker) -> UInt64 {
    return FfiConverterTypeTracker.lower(value)
}




public struct ApiEndpoints: Equatable, Hashable {
    public var trackBenefitProvider: String
    public var trackDistributionChannel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(trackBenefitProvider: String, trackDistributionChannel: String) {
        self.trackBenefitProvider = trackBenefitProvider
        self.trackDistributionChannel = trackDistributionChannel
    }

    
}

#if compiler(>=6)
extension ApiEndpoints: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApiEndpoints: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApiEndpoints {
        return
            try ApiEndpoints(
                trackBenefitProvider: FfiConverterString.read(from: &buf), 
                trackDistributionChannel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ApiEndpoints, into buf: inout [UInt8]) {
        FfiConverterString.write(value.trackBenefitProvider, into: &buf)
        FfiConverterString.write(value.trackDistributionChannel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiEndpoints_lift(_ buf: RustBuffer) throws -> ApiEndpoints {
    return try FfiConverterTypeApiEndpoints.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiEndpoints_lower(_ value: ApiEndpoints) -> RustBuffer {
    return FfiConverterTypeApiEndpoints.lower(value)
}


public struct SdkConfig: Equatable, Hashable {
    public var apiBaseUrl: String
    public var apiEndpoints: ApiEndpoints
    public var trackingPlatformType: String?
    public var distributionChannel: String?
    public var sdkId: String?
    public var customSelectors: [String]
    public var debounceDelay: UInt32
    public var debug: Bool
    public var trackClicks: Bool
    public var trackPageviews: Bool
    public var trackPageClose: Bool
    public var trackTimeSpent: Bool
    public var trackHeatmap: Bool
    public var trackChurnPoint: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(apiBaseUrl: String, apiEndpoints: ApiEndpoints, trackingPlatformType: String?, distributionChannel: String?, sdkId: String?, customSelectors: [String], debounceDelay: UInt32, debug: Bool, trackClicks: Bool, trackPageviews: Bool, trackPageClose: Bool, trackTimeSpent: Bool, trackHeatmap: Bool, trackChurnPoint: Bool) {
        self.apiBaseUrl = apiBaseUrl
        self.apiEndpoints = apiEndpoints
        self.trackingPlatformType = trackingPlatformType
        self.distributionChannel = distributionChannel
        self.sdkId = sdkId
        self.customSelectors = customSelectors
        self.debounceDelay = debounceDelay
        self.debug = debug
        self.trackClicks = trackClicks
        self.trackPageviews = trackPageviews
        self.trackPageClose = trackPageClose
        self.trackTimeSpent = trackTimeSpent
        self.trackHeatmap = trackHeatmap
        self.trackChurnPoint = trackChurnPoint
    }

    
}

#if compiler(>=6)
extension SdkConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSdkConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SdkConfig {
        return
            try SdkConfig(
                apiBaseUrl: FfiConverterString.read(from: &buf), 
                apiEndpoints: FfiConverterTypeApiEndpoints.read(from: &buf), 
                trackingPlatformType: FfiConverterOptionString.read(from: &buf), 
                distributionChannel: FfiConverterOptionString.read(from: &buf), 
                sdkId: FfiConverterOptionString.read(from: &buf), 
                customSelectors: FfiConverterSequenceString.read(from: &buf), 
                debounceDelay: FfiConverterUInt32.read(from: &buf), 
                debug: FfiConverterBool.read(from: &buf), 
                trackClicks: FfiConverterBool.read(from: &buf), 
                trackPageviews: FfiConverterBool.read(from: &buf), 
                trackPageClose: FfiConverterBool.read(from: &buf), 
                trackTimeSpent: FfiConverterBool.read(from: &buf), 
                trackHeatmap: FfiConverterBool.read(from: &buf), 
                trackChurnPoint: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SdkConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.apiBaseUrl, into: &buf)
        FfiConverterTypeApiEndpoints.write(value.apiEndpoints, into: &buf)
        FfiConverterOptionString.write(value.trackingPlatformType, into: &buf)
        FfiConverterOptionString.write(value.distributionChannel, into: &buf)
        FfiConverterOptionString.write(value.sdkId, into: &buf)
        FfiConverterSequenceString.write(value.customSelectors, into: &buf)
        FfiConverterUInt32.write(value.debounceDelay, into: &buf)
        FfiConverterBool.write(value.debug, into: &buf)
        FfiConverterBool.write(value.trackClicks, into: &buf)
        FfiConverterBool.write(value.trackPageviews, into: &buf)
        FfiConverterBool.write(value.trackPageClose, into: &buf)
        FfiConverterBool.write(value.trackTimeSpent, into: &buf)
        FfiConverterBool.write(value.trackHeatmap, into: &buf)
        FfiConverterBool.write(value.trackChurnPoint, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSdkConfig_lift(_ buf: RustBuffer) throws -> SdkConfig {
    return try FfiConverterTypeSdkConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSdkConfig_lower(_ value: SdkConfig) -> RustBuffer {
    return FfiConverterTypeSdkConfig.lower(value)
}


public struct TrackEvent: Equatable, Hashable {
    public var name: String
    public var properties: [TrackProperty]
    public var timestampMs: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, properties: [TrackProperty], timestampMs: Int64) {
        self.name = name
        self.properties = properties
        self.timestampMs = timestampMs
    }

    
}

#if compiler(>=6)
extension TrackEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrackEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrackEvent {
        return
            try TrackEvent(
                name: FfiConverterString.read(from: &buf), 
                properties: FfiConverterSequenceTypeTrackProperty.read(from: &buf), 
                timestampMs: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TrackEvent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterSequenceTypeTrackProperty.write(value.properties, into: &buf)
        FfiConverterInt64.write(value.timestampMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackEvent_lift(_ buf: RustBuffer) throws -> TrackEvent {
    return try FfiConverterTypeTrackEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackEvent_lower(_ value: TrackEvent) -> RustBuffer {
    return FfiConverterTypeTrackEvent.lower(value)
}


public struct TrackProperty: Equatable, Hashable {
    public var key: String
    public var value: Property

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: Property) {
        self.key = key
        self.value = value
    }

    
}

#if compiler(>=6)
extension TrackProperty: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrackProperty: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrackProperty {
        return
            try TrackProperty(
                key: FfiConverterString.read(from: &buf), 
                value: FfiConverterTypeProperty.read(from: &buf)
        )
    }

    public static func write(_ value: TrackProperty, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterTypeProperty.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackProperty_lift(_ buf: RustBuffer) throws -> TrackProperty {
    return try FfiConverterTypeTrackProperty.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackProperty_lower(_ value: TrackProperty) -> RustBuffer {
    return FfiConverterTypeTrackProperty.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Property: Equatable, Hashable {
    
    case string(value: String
    )
    case number(value: Double
    )
    case bool(value: Bool
    )



}

#if compiler(>=6)
extension Property: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProperty: FfiConverterRustBuffer {
    typealias SwiftType = Property

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Property {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .string(value: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .number(value: try FfiConverterDouble.read(from: &buf)
        )
        
        case 3: return .bool(value: try FfiConverterBool.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Property, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .string(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        
        case let .number(value):
            writeInt(&buf, Int32(2))
            FfiConverterDouble.write(value, into: &buf)
            
        
        case let .bool(value):
            writeInt(&buf, Int32(3))
            FfiConverterBool.write(value, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProperty_lift(_ buf: RustBuffer) throws -> Property {
    return try FfiConverterTypeProperty.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProperty_lower(_ value: Property) -> RustBuffer {
    return FfiConverterTypeProperty.lower(value)
}



public enum SdkError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidConfig(message: String)
    
    case InvalidEvent(message: String)
    
    case StorageError(message: String)
    
    case NetworkError(message: String)
    
    case SerializationError(message: String)
    
    case Unknown(message: String)
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SdkError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSdkError: FfiConverterRustBuffer {
    typealias SwiftType = SdkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SdkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidConfig(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidEvent(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .StorageError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .NetworkError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .SerializationError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Unknown(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SdkError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidConfig(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidEvent(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .StorageError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .NetworkError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .SerializationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Unknown(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSdkError_lift(_ buf: RustBuffer) throws -> SdkError {
    return try FfiConverterTypeSdkError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSdkError_lower(_ value: SdkError) -> RustBuffer {
    return FfiConverterTypeSdkError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTrackProperty: FfiConverterRustBuffer {
    typealias SwiftType = [TrackProperty]

    public static func write(_ value: [TrackProperty], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTrackProperty.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TrackProperty] {
        let len: Int32 = try readInt(&buf)
        var seq = [TrackProperty]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTrackProperty.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_themiracle_tracking_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_themiracle_tracking_checksum_method_tracker_flush() != 11445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_themiracle_tracking_checksum_method_tracker_set_consent() != 62069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_themiracle_tracking_checksum_method_tracker_set_session() != 54322) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_themiracle_tracking_checksum_method_tracker_set_user() != 55364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_themiracle_tracking_checksum_method_tracker_track() != 18697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_themiracle_tracking_checksum_constructor_tracker_new() != 57787) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureThemiracleTrackingInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all